name: document_web_crawler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - llama-index==0.10.7
    - beautifulsoup4==4.12.3
    - selenium==4.18.1
    - webdriver-manager==4.0.1
    - python-dotenv==1.0.1
    - chromadb==0.4.22
    - sqlalchemy==2.0.27
    - psycopg2-binary==2.9.9
    - pytest==8.0.2 